# Generated by Django 4.2.8 on 2023-12-19 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Номер должен быть такого формата: '+996xxxxxxxxx'.", regex='^\\+996\\d{9}$')]),
        ),
    ]
