# Generated by Django 4.2.8 on 2023-12-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='avatar_pics/'),
        ),
    ]
