# Generated by Django 4.2.8 on 2023-12-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dbiyaguqb/image/upload/v1703181238/media/default/default.jpg', max_length=300, null=True, upload_to='avatar_pics/'),
        ),
    ]
